name: Build Windows App
on: [push, workflow_dispatch] # workflow_dispatch erlaubt manuelles Starten

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Standalone EXE
        run: dotnet publish CS2ShaderCleaner.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=false -o ./dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CS2-Shader-Cleaner-Executable
          path: ./dist/CS2ShaderCleaner.exe
